import React, { useState } from 'react';
import { FileText, Plus, Book, Quote, ArrowRight, Sparkles, AlertCircle, RefreshCw } from 'lucide-react';
import { apiJson } from '../lib/api';

const DEFAULT_PAPERS = [
  {
    id: 1,
    title: 'Attention Is All You Need',
    authors: 'Vaswani et al.',
    year: 2017,
    subject: 'Deep Learning / NLP',
    abstract: 'We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable.',
    findings: ['Introduces the Transformer architecture.', 'Uses multi-head self-attention instead of recurrence.', 'Enabled faster training and better translation quality.']
  },
  {
    id: 2,
    title: 'Deep Residual Learning for Image Recognition',
    authors: 'He et al.',
    year: 2015,
    subject: 'Computer Vision',
    abstract: 'We present a residual learning framework to ease the training of networks that are substantially deeper than those previously used. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions.',
    findings: ['Introduced skip connections (residual blocks).', 'Enabled training of very deep networks.', 'Strong image classification performance on ILSVRC 2015.']
  }
];

export default function ResearchHub({ refreshData }) {
  const [papers, setPapers] = useState(DEFAULT_PAPERS);
  const [selectedPaperId, setSelectedPaperId] = useState(1);
  const [uploadTitle, setUploadTitle] = useState('');
  const [uploadAbstract, setUploadAbstract] = useState('');
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState('');

  const [citeTitle, setCiteTitle] = useState('Attention Is All You Need');
  const [citeAuthor, setCiteAuthor] = useState('Vaswani, A.');
  const [citeYear, setCiteYear] = useState('2017');
  const [citeJournal, setCiteJournal] = useState('Advances in Neural Information Processing Systems');
  const [citationResult, setCitationResult] = useState('');
  const [citationError, setCitationError] = useState('');
  const [generatingCitation, setGeneratingCitation] = useState(false);

  const handleAddPaper = async (e) => {
    e.preventDefault();
    if (!uploadTitle || !uploadAbstract) return;

    setUploading(true);
    setUploadError('');
    try {
      const result = await apiJson('/api/ai/hub', {
        method: 'POST',
        body: JSON.stringify({
          agent: 'research',
          action: 'summarize_paper',
          payload: { title: uploadTitle, abstract: uploadAbstract }
        })
      });

      const newPaper = {
        id: Date.now(),
        title: uploadTitle,
        authors: 'Student Upload',
        year: new Date().getFullYear(),
        subject: 'General Research',
        abstract: uploadAbstract,
        findings: Array.isArray(result.findings) && result.findings.length
          ? result.findings
          : [result.summary || 'Summary generated by Polaris Research Agent.']
      };
      setPapers(prev => [newPaper, ...prev]);
      setSelectedPaperId(newPaper.id);
      setUploadTitle('');
      setUploadAbstract('');
    } catch (err) {
      console.error('Paper processing failed:', err);
      setUploadError(err.message || 'AI paper processing is unavailable.');
    } finally {
      setUploading(false);
    }
  };

  const handleGenerateCitation = async (format) => {
    setGeneratingCitation(true);
    setCitationError('');
    setCitationResult('');
    try {
      const result = await apiJson('/api/ai/hub', {
        method: 'POST',
        body: JSON.stringify({
          agent: 'research',
          action: 'generate_citation',
          payload: {
            format,
            author: citeAuthor,
            year: citeYear,
            title: citeTitle,
            journal: citeJournal
          }
        })
      });
      setCitationResult(result.citation || '');
    } catch (err) {
      console.error('Citation generation failed:', err);
      setCitationError(err.message || 'AI citation generation is unavailable.');
    } finally {
      setGeneratingCitation(false);
    }
  };

  const activePaper = papers.find(p => p.id === selectedPaperId) || papers[0];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <header>
        <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '0.25rem' }}>🧠 Research Library Agent</h1>
        <p style={{ color: 'var(--text-secondary)' }}>Extract PDF abstracts, manage bibliography files, and automatically generate academic citations.</p>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '2rem' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          <section className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <h3 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Plus size={16} style={{ color: 'var(--primary)' }} />
              Upload PDF or Notes file
            </h3>

            <form onSubmit={handleAddPaper} style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <input
                type="text"
                placeholder="Paper Title (e.g. ImageNet Classification)"
                value={uploadTitle}
                onChange={e => setUploadTitle(e.target.value)}
                style={{ width: '100%', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none' }}
              />
              <textarea
                placeholder="Paste abstract or introductory text here..."
                value={uploadAbstract}
                onChange={e => setUploadAbstract(e.target.value)}
                style={{ width: '100%', height: '80px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none', resize: 'none' }}
              />
              {uploadError && (
                <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', fontSize: '0.8rem', color: 'var(--error)' }}>
                  <AlertCircle size={14} />
                  {uploadError}
                </div>
              )}
              <button
                type="submit"
                disabled={uploading || !uploadTitle || !uploadAbstract}
                className="btn-secondary"
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.6rem', justifyContent: 'center' }}
              >
                {uploading ? 'Processing with AI...' : 'Process Document'}
              </button>
            </form>
          </section>

          <section className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <h3 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Book size={16} style={{ color: 'var(--secondary)' }} />
              Reference Document Shelf
            </h3>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', overflowY: 'auto', maxHeight: '300px' }}>
              {papers.map(p => (
                <div
                  key={p.id}
                  onClick={() => setSelectedPaperId(p.id)}
                  className="glass-card"
                  style={{
                    cursor: 'pointer',
                    background: selectedPaperId === p.id ? 'rgba(217, 70, 239, 0.06)' : 'rgba(255,255,255,0.01)',
                    borderColor: selectedPaperId === p.id ? 'var(--secondary)' : 'rgba(255,255,255,0.05)',
                    padding: '0.75rem'
                  }}
                >
                  <strong style={{ fontSize: '0.88rem', color: 'var(--text-primary)', display: 'block' }}>{p.title}</strong>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '0.25rem', fontSize: '0.72rem', color: 'var(--text-secondary)' }}>
                    <span>{p.authors} ({p.year})</span>
                    <span style={{ color: 'var(--primary)' }}>{p.subject}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {activePaper && (
            <section className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <FileText size={18} style={{ color: 'var(--accent)' }} />
                  <h3 style={{ fontSize: '1.2rem' }}>Summary Details</h3>
                </div>
                <span style={{ fontSize: '0.7rem', color: 'var(--accent)', background: 'rgba(245,158,11,0.1)', padding: '0.1rem 0.4rem', borderRadius: '4px', border: '1px solid rgba(245,158,11,0.2)' }}>
                  Active Paper
                </span>
              </div>

              <div>
                <strong style={{ fontSize: '1.05rem', color: 'var(--text-primary)', display: 'block' }}>{activePaper.title}</strong>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginTop: '0.2rem' }}>Authors: {activePaper.authors} | Published: {activePaper.year}</span>
              </div>

              <div style={{ borderTop: '1px solid var(--panel-border)', paddingTop: '0.75rem' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>Document Abstract</span>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.5, marginTop: '0.25rem', fontStyle: 'italic' }}>
                  "{activePaper.abstract}"
                </p>
              </div>

              <div>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 'bold' }}>Key Findings</span>
                <ul style={{ paddingLeft: '1.25rem', fontSize: '0.82rem', color: 'var(--text-secondary)', marginTop: '0.25rem', display: 'flex', flexDirection: 'column', gap: '0.3rem' }}>
                  {(activePaper.findings || []).map((f, idx) => <li key={idx}>{f}</li>)}
                </ul>
              </div>
            </section>
          )}

          <section className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <h3 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Quote size={16} style={{ color: 'var(--primary)' }} />
              Auto-Citation Formatter
            </h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
              <input type="text" placeholder="Author (e.g. Vaswani, A.)" value={citeAuthor} onChange={e => setCiteAuthor(e.target.value)} style={{ background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none' }} />
              <input type="text" placeholder="Year (e.g. 2017)" value={citeYear} onChange={e => setCiteYear(e.target.value)} style={{ background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none' }} />
              <input type="text" placeholder="Title (e.g. Attention Is All You Need)" value={citeTitle} onChange={e => setCiteTitle(e.target.value)} style={{ gridColumn: '1 / -1', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none' }} />
              <input type="text" placeholder="Journal / Conference" value={citeJournal} onChange={e => setCiteJournal(e.target.value)} style={{ gridColumn: '1 / -1', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '0.6rem 0.75rem', color: 'var(--text-primary)', fontSize: '0.85rem', outline: 'none' }} />
            </div>

            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
              {['APA', 'MLA', 'Chicago'].map(format => (
                <button key={format} className="btn-secondary" disabled={generatingCitation} onClick={() => handleGenerateCitation(format)} style={{ fontSize: '0.75rem' }}>
                  {generatingCitation ? 'Generating...' : format}
                </button>
              ))}
            </div>

            {citationError && (
              <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', fontSize: '0.8rem', color: 'var(--error)' }}>
                <AlertCircle size={14} />
                {citationError}
              </div>
            )}

            {citationResult && (
              <div className="glass-card" style={{ padding: '0.75rem', fontSize: '0.82rem', color: 'var(--text-secondary)', fontFamily: 'monospace', lineHeight: 1.5 }}>
                {citationResult}
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}
